#!~/anaconda2/bin/python

# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1, 2 and 10, the first terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not 
# exceed N, find the sum of the even-valued terms.
#    
# Input Format
#    
# First line contains T that denotes the number of test cases. This is 
# followed by T lines, each containing an integer, N. 
# 
# Constraints
# 
# 1 <= T <= 1e5
# 10 <= N <= 4e16
# 
# Output Format
# 
# Print the required answer for each test case.
# 


import sys

def main():
    test_cases = int(raw_input().strip())
    
    for case in xrange(test_cases):
        N = int(raw_input().strip())


main()
